apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: {{ .Values.container.labels }}
  name: "{{ .Release.Name }}-deployment"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.container.labels }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.container.labels }}
    spec:
      containers:
      - image:  {{ .Values.container.image }}
        name: {{ .Values.container.name }}
        resources: {}
status: {}